# Generated by Django 3.0.3 on 2020-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
